version: "3.9"

services:
    db:
        image: postgres
        container_name: myairline-db
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: myAirline