name: myAirline-userService CI

run-name: ${{ github.event.head_commit.message }}
on: 
  push: 
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v2.5.1
        with: 
          distribution: 'temurin'
          java-version: '17'
      - run: docker-compose -f "docker-compose-db.yml" up -d
      - run: gradle clean build